# The use of the correct number of significant figures in calculations. {#sec-chapter2}

In @sec-chapter1 we have learnt about significant figures and why they are important in understanding the confidence we have in a value.

Now we need to learn the rules to how many significant figures we should use after doing calculations.

There are different rules for how we handle significant figures depending upon the type of calculation we have done. Freqently we may have more than one step in a calculation, and therefore we need to be concious of the appropriate significant figures in each step.



## Significant figures in addition and subtraction {#sec-sfaddsub}

When adding or subtracting values, the number of decimal places in the result should be the same as the value with the least number of decimal places in your calculation.

We cannot add precision, I can't measure something with a meter rule with 1 cm increments, a 15 cm rule with 1 mm increments and a micrometer with 1 μm increments and then add them together and expect to have a result with 1 μm precision. The result will be limited by the least precise measurement.

::: {#tip-scales .callout-tip title="Significant figures in addition and subtraction."}
When adding or subtracting values, the number of decimal places in the result should be the same as the value with the least number of decimal places in your calculation.
:::

::: {.callout-caution title="Examples of significant figures in addition and subtraction."}

- Convert 20 ºC to Kelvin.

We know our measured temperature to 0 decimal places, therefore our answer should be to 0 decimal places.

T = 20 ºC + 273.15 K = 293 K

- An ideal gas was heated with 1.75 kJ of energy an allowed to do 250 J of work. What is the change in internal energy of the gas?

In this case we have different units, so if we convert 250 J to kJ we have 0.250 kJ. The least number of decimal places is 2, therefore our answer should be to 2 decimal places.

$\Delta U = 1.75 \textrm{ kJ} - 0.250 \textrm{ kJ} = 1.50 \textrm{ kJ}$

This unit conversion kJ to J (or vice versa) is common in thermodynamics calculations where $\Delta H$ is usually reported in kJ mol$^{-1}$, but $\Delta S$ is usually reported in J K mol$^{-1}$.

It is easy to forget the significant zero at the end of this number as usually our calculator will not report it, but including it gives us our answer to a  higher, more appropriate, precision.

:::

### Exercises with addition and subtraction examples.

#### Self check on our learning so far. {#sec-SelfcheckSFaddsub}

::: {.callout-note collapse="true"}
## What is 15.4 g + 0.16 g to the correct number of significant figures?

15.6 g

The rule for adding and subtracting is that the answer should be reported to the least number of decimal places in the calculation. In this case 15.4 g has 1 decimal place, and 0.16 g has 2 decimal places, so our answer should be reported to 1 decimal place.

:::

::: {.callout-note collapse="true"}
## What is -154.3 kJ mol$^{-1}$ + 894.2 J mol$^{-1}$ to the correct number of significant figures?

-153.4 kJ mol$^{-1}$

Here we have different units, so if we convert 894.2 J mol$^{-1}$ to kJ mol$^{-1}$ we have 0.8942 kJ mol$^{-1}$. 

Now we can compare the number of decimal places in each value. -154.3 kJ mol$^{-1}$ has 1 decimal place, and 0.8942 kJ mol$^{-1}$ has 4 decimal places, so keeping the fewest decimal places, our answer should be reported to 1 decimal place.

:::

The following are molar masses of some common elements. Use these values to answer the following questions.


|| $R_A$ / g mol$^{-1}$ |
|:---:|:------:|
| H | 1.00794 |
| C | 12.011 |
| O | 15.9994 |
| N | 14.0067 |
| Cl | 35.45 |


: A selection of atomic masses of common elements. {#tbl-atomicmassescommon}    

:::{.callout-note collapse="true"}
## What is the molar mass of HCl to the correct number of significant figures?

36.46 g mol$^{-1}$

35.45 g mol$^{-1}$ + 1.00794 g mol$^{-1}$ = ~~36.45794 g mol~~$^{-1}$
 = 36.46 g mol$^{-1}$


Cl has the least number of decimal places (2), so our answer should only be reported to 2 decimal places.
:::

Given we should now be in the habit of reporting our answers to the correct number of significant figures, this is no longer going to be asked in the following exercises, but we should still be concious of the number of significant figures in our answers.

:::{.callout-note collapse="true"}
## What is the molar mass of C$_2$H$_5$OH?

46.064 g mol$^{-1}$

Carbon's molar mass has 3 decimal places, hydrogen's molar mass has 5 decimal places and oxygen's molar mass has 4 decimal places. 

In addition questions our answer should be reported to the fewest decimal places, which in this case is 3.
:::

:::{.callout-note collapse="true"}
## What is the molar mass of C$_6$H$_{12}$O$_6$?

180.158 g mol$^{-1}$

Once you get used to the idea of handling signficant figures you will be able to perform your calculations, then correct your values to the correct number of significant figures when reporting.

Here Carbon has 3 decimal places, so the answer should be reported to 3 decimal places, even if the value coming from a calculator would be 180.15768.
:::

:::{.callout-note collapse="true"}
## What is the molar mass of C$_{12}$H$_8$N$_2$?

180.209 g mol$^{-1}$


Again carbon limits the number of decimal places to give in our answer.
:::

:::{.callout-note collapse="true"}
## What is the molar mass of C$_{12}$H$_{22}$O$_{11}$?

342.300 g mol$^{-1}$

It is important to remember to include significant zeros if they are there. These are easy to remember because there were non zero numbers after them, but remember to write them down.
:::


#### Self assessment question on significant figures in addition and subtraction.

Please remember you can refresh this question.

```{=html}
<iframe src="https://numbas.mathcentre.ac.uk/question/210135/sig-figs-add-sub/embed/?token=504985f6-ad65-4e25-8415-4a61de7d9766" width=100% height="400"></iframe>
```

Question in context:

```{=html}
<iframe src="https://numbas.mathcentre.ac.uk/question/210791/calculate-molar-mass/embed/?token=6efdf064-52e6-48f7-bd63-af431e8140c2" width = 100% height = "760"></iframe>
```

## Significant figures in multiplication and division {#sec-sfmuldiv}

When multiplying or dividing values, the number of significant figures in the result should be the same as the value with the least number of significant figures in your calculation.

First we need to quickly count the number of significant figures in each value. If we have a unit conversion (such as mm to cm) then this is 'exact' and does not change the number of significant figures in our value. Some unit conversions have limited significant figures, others are precise. In either case it is always a good habit to use more significant figures in constants than in our other values.

::: {#tip-scales .callout-tip title="Significant figures in multiplication and division."}
When multiplying or dividing values, the number of significant figures in the result should be the same as the value with the least number of significant figures in your calculation.
:::

::: {.callout-caution title="Example of significant figures in multiplication and division - the ideal gas law."}

- Determine the number of moles of gas in a cylinder with a volume of exactly 2.52 L at a pressure of 50.24 bar and a temperature of 273 K.

Here we need to do a couple of unit conversions to get our values into base SI units. 

The volume is already in L, which is a derived unit, but we need to convert it to m$^3$. 1 L $\equiv$ 1 dm$^3$ = 1 x 10$^{-3}$ m$^3$, so we have 2.52 L = 2.52 x 10$^{-3}$ m$^3$. 
This is an exact conversion, so the number of significant figures in our value does not change.
Recall that the volume is described as "exactly" 2.52 L, so we have 'infinite' significant figures in our volume.

The pressure is in bar, which is not an SI unit, so we need to convert it to Pa. 1 bar = 1 x 10$^5$ Pa, so we have 50.24 bar = 5.024 x 10$^6$ Pa. This is also an exact conversion.
The pressure has 4 significant figures, so our pressure in bar will also have 4 significant figures.

Using the ideal gas law, we can calculate the number of moles of gas in the cylinder.

$pV = nRT$
so $n = \frac{pV}{RT}$

Putting in our values:

$$n = \frac{5.024 \times 10^6 \textrm{ Pa} \times 2.52 \times 10^{-3} \textrm{ m}^3}{8.31446 \textrm{ J K}^{-1} \textrm{ mol}^{-1} \times 273 \textrm{ K}}$$

$n = 5.58 \textrm{ mol}$

Temperature only has 3 significant figures, so our answer should be reported to 3 significant figures.
:::


::: {.callout-caution title="Example of significant figures in multiplication and division - heat capacity."}

- Determine the energy put into a system when a 1.000 kg block of copper is heated from 20.16 ºC to 60.52 ºC. The specific heat capacity of copper is 385 J kg$^{-1}$ K$^{-1}$.

We can calculate the energy put into the system using the equation:

$q = m c \Delta T$

First we need to determine the change in temperature, $\Delta T$.

$\Delta T = T_{\textrm{final}} - T_{\textrm{initial}}$

$\Delta T = 60.52 ºC - 20.16 ºC = 40.36 ºC$

We've followed the rules for addition and subtraction, so our answer has 2 decimal places, which is the same as the least number of decimal places in our calculation.

Now we can calculate the energy put into the system, $q$.

$q = 1.000 \textrm{ kg} \times 385 \textrm{ J kg}^{-1} \textrm{ K}^{-1} \times 40.36 \textrm{ K}$

The mass has 4 significant figures, the specific heat capacity has 3 significant figures, and the temperature change has 4 significant figures. The least number of significant figures in our calculation is 3, so our answer should be reported to 3 significant figures.

$q = 15.5 \textrm{ kJ}$

Note: I've changed my units to kJ to make reporting to 3 significant figures easier. If I had left my answer in J, I would have reported it as 15.5 $\times$ 10³ J, which is not as clear (and is more to type).
:::

### Exercises with multiplication and division examples.

#### Self check on our learning so far. {#sec-SelfcheckSFmultdiv}

:::{.callout-note collapse="true"}
## If each side of a rectangle was measured to be 2.34 cm and 1.2 cm, what is the area?

A = 2.8 cm$^2$

The area of a rectangle is given by $A = l \times w$, so from our calculator we get a value of 2.808 cm$^2$. Since one of our sides only has 2 significant figures, using our rule of using the fewest significant figures, our answer should be reported to 2 significant figures.
:::

:::{.callout-note collapse="true"}
## What is the volume of a cylinder with a diameter of 2.3 cm and a height of 12.4 cm?

V = 52 cm$^3$

On the surface this is an easy calculation following our rules of significant figures we retain the fewest significant figures in our answer, which is 2. 

You might be tempted to use the radius of the circle, and 'half' the diameter, but in doing this we can get into a mess with our significant figures because we can't gain significant figures by dividing by 2. 

Instead we can use the diameter directly in our calculation, $V = \frac{\pi d^2 h}{4}$ which simplifies the significant figure handling.

This shows that is is often easiest to use algebraic rearrangements to avoid having to do extra calculations which may introduce complications in our consideration of significant figures.
:::

::: {.callout-note collapse="true"}
## Determine the rate constant of diffusion, $k_d$ at 278 K, if the viscosity of the medium, $\eta$, is 1.518 mPa s, given $k_d = \frac{8RT}{3\eta}$.

$k_d = 4.06 \times 10^{6}$ m$^3$ s$^{-1}$ = 4.06 \times 10$^{9}$ dm$^3$ s$^{-1}$

This is a more challenging question as you won't hve come across this equation before, but the principles are the same. This is a multiplication and division question, so we need to consider the number of significant figures in each value, and report our answer to the fewest number of significant figures in our calculation.

The integers, 8 and 3 are exact values, so can be considered to have infinite significant figures.

When values are large some poeple want to write 4 060 000 (3sf) but given our rule that if you write a digit it is significant this answer is actually 7 significant figures.
:::

#### Self assessment question on significant figures in multiplication and division.

Please remember you can refresh this question.

## Significant figures in logarithms {#sec-sflog}

Significant figures in logs and lns are a little different to the rules for addition, subtraction, multiplication and division because we have to think about the 'value' when accounting for how many significant figures we have in our answer.

::: {#tip-scales .callout-tip title="Significant figures in logs and lns."}
When taking logs we usually gain 1 significant figure, however if the ‘logged value’ is between 0 and the base then we do not gain a significant figure.
:::

Practically what does this mean? and why the do we sometimes gain a significant figure? The following example using $\log_{10}$ will help to explain this.

::: {.callout-caution title="Example of significant figures in logs and lns."}

Determine $\log (2.234)$, $\log(22.34)$ and $\log(223.4)$ to the correct number of significant figures.

Our first example is $\log(2.234)$. The value of $\log(2.234)$ is 0.3490831688.... 

The value we are taking the log of has 4 significant figures, so our answer should have 4 significant figures. Therefore we report our answer as 0.3491.

Now, if I take the log of 22.34 I can also write this as $\log(2.234 \times 10^1)$.

Using our 'rules of logs', we can write this as $\log(2.234) + \log(10^1) = 0.3491 + 1 = 1.3491$.

Since our value of $\log(10^1)$ is an exact value, it can be considered to have infinite significant figures, and we can add these values according to the rules in @sec-sfaddsub.

Finally, if I take the log of 223.4 I can also write this as $\log(2.234 \times 10^2)$. The value we are taking the log of has 4 significant figures, so our answer should have 4 significant figures. Therefore we report our answer as 2.3491.

You can see why we gain a significant figure when taking the log of a value greater than 10, but not when taking the log of a value less than 10. The 'value' of the number we are taking the log of is important in determining how many significant figures we have in our answer.

The same principle works if we have very small numbers, for example $\log(0.002234)$ which we can write as $\log(2.234 \times 10^{-3}) = \log(2.234) + \log(10^{-3}) = 0.3491 - 3 = -2.6509$.
:::


### Exercises with logarythm examples.

#### Self check on our learning so far.

:::{.callout-note collapse="true"}
## Calculate log 5.34.

0.728

Because 5.34 is between 1 and the base (in this case base 10) we do not gain a significant figure in our calculation.
:::

:::{.callout-note collapse="true"}
## Calculate ln 7.156.

1.9680

In this case we do gain a significant figure as our value is greater than the base (in this case base e). A quick way to know if we are bigger than the base is if our calculated logarithm is greater than 1.
:::

:::{.callout-note collapse="true"}
## Determine the pH of a 5.59 µM solution of a strong acid. You may assume the activity coefficient is 1.

pH = 5.253

$\textrm{pH} = -\log {\{H^+\}}$

Our concentration may also be written as 5.59 $\times$ 10$^{-6}$, this value is less than 1, so we will gain a significnant figure.
:::

#### Self assessment question on significant figures with logarythms.

## Significant figures in exponents, powers and roots. {#sec-sfpowers}

::: {#tip-scales .callout-tip title="Significant figures with powers and roots."}
Squaring, cubing, or rooting a value our answer should have the same number of significant figures as the value we operated on.
:::

This is easiest to think about in terms of squaring or cubing, where we can think about things in terms of multiplying values.

:::{.callout-caution title="Example of significant figures in powers - volume."}
* Determine the volume of a sphere with diameter 4.52 cm.

Again, I'm going to use the equation for volume with diameter. The volume of a sphere is given by: $V = \frac{4}{3}\pi r^3$, this can be written in terms of diameter, $d$, as: $V = \frac{1}{6}\pi d^3$

$\pi$ is a number with 'infinite' significant figures.

So in our calculation our volume will carry the same number of signifiant figures as the diameter.

V = 48.4 cm$^{3}$

:::

This principle stands with any power, be it integers, fractions (square and cube roots), or negative powers. The number of significant figures in our answer should be the same as the number of significant figures in the value we are operating on.

If you recall, in some circumstances when taking logarythms we sometimes gained a significant figure. When taking exponents (the reciprocal function of logs) then this means that we sometimes need to loose a significant figure.

::: {#tip-scales .callout-tip title="Significant figures with exponents."}
When taking an antilog (so for example $10^x$ or $e^x$) we should retain the same number of significant figures if our exponent is between -1 and 1.

If our exponent is less than -1 or greater than 1 then we should loose a significant figure.
:::

Why is the rule between -1 and 1?

This is because we can write negative exponents as positive exponents in a fraction, so $e^{-x} = \frac{1}{e^x}$.

For ease this first example is 'undoing' one of our examples from @sec-sflog.

::: {.callout-caution title="Example of significant figures exponents."}

Determine $10^{0.3491.}$ and  $10^{1.3491}$ to the correct number of significant figures.

This is the type of question you see if calculating activity from pH.

For our first example $10^{0.3491}$ our exponent is between 0 and 1, so we should retain the same number of significant figures in our answer.

$10^{0.3491} = 2.234$

However, for our second example $10^{1.3491}$ our exponent is greater than 1, so we should loose a significant figure in our answer, so 5 significant figures in our exponent gives us 4 significant figures in our answer.

$10^{1.3491} = 22.34$
:::


### Exercises with exponents, powers and roots.

#### Self check on our learning so far. {#sec-SelfcheckSFpowers}

:::{.callout-note collapse="true"}
## Calculate $e^{0.728}$.

2.07

Because our power is between 0 and 1, we should retain the same number of significant figures in our answer.
:::


:::{.callout-note collapse="true"}
## Calculate $e^{-0.38}$.

0.68 

Because our power is between -1 and 1, we should retain the same number of significant figures in our answer.

Rembember when we have a negative exponent we can write it as a positive exponent in a fraction, so $e^{-0.38} = \frac{1}{e^{0.38}}$.
:::

:::{.callout-note collapse="true"}
## Calculate $10^{4.5718}$.

37.31 $\times$ 10$^3$  

This is one of the cases where our exponent is greater than 1, so we should loose a significant figure in our answer, so 5 significant figures in our exponent gives us 4 significant figures in our answer.

Because writing our answer as 37310 would contain 5 significant figures, (even if we think we've rounded it to 4 significant figures) we need to write our answer in scientific notation to show that we have 4 significant figures in our answer.
:::

:::{.callout-note collapse="true"}
## Calculate $10^{-6.18}$.

6.6 $\times$ 10$^{-7}$

This is one of the cases where our exponent is less than -1, so we should loose a significant figure in our answer, so 3 significant figures in our exponent gives us 2 significant figures in our answer.
:::

:::{.callout-note collapse="true"}
## Calculate $10^{0.477}$.

3.0

We have lost a significant figure, but we need to remember to include the significant zero in our answer.
:::

Now a chemistry example

:::{.callout-note collapse="true"}
## Determine the activity of H$^+$ in a solution with pH = 5.25.

$\{\textrm{H}^+\} = 5.6 \times 10^{-6}$

Recall that $\textrm{pH} = -\log \{H^+\}$, so we can rearrange this to give us $\{H^+\} = 10^{-\textrm{pH}}$.

We have a negative exponent, and it is less than -1, so we should loose a significant figure in our answer, so 3 significant figures in our exponent gives us 2 significant figures in our answer.

Note: curly brackets are used to denote activity, and square brackets are used to denote concentration.

:::



## Significant figures in mixed calculations {#sec-sfmixed}

Many calculations we see in chemistry involve a mixture of different mathematical operators, which you have learned to handle in school using the rule of BODMAS/BIDMAS (Brackets, Order/Indices, Division and Multiplication, Addition and Subtraction).

::: {#tip-scales .callout-tip title="Significant figures in mixed calculations."}
When we have a mixed calculation we need to follow the appropriate number of significant figures appropriate in a stepwise (BIDMAS/BODMAS) manner, and then report our final answer to the appropriate number of significant figures.

:::

When we have a mixed calculation we need to follow the appropriate number of significant figures appropriate in a stepwise manner, and then report our final answer to the appropriate number of significant figures.

Practically we do not 'round' our answer at each step, (because of the probability of making an error in our input) and only round our final answer to the appropriate number of significant figures.

Common examples of mixed calculations in chemistry involve temperature, where the conversion between Celsius and Kelvin is frequently used. Thermodynamics also gives us $\Delta G = \Delta H - T \Delta S$, further kinetics calculations frequently involve both multiplication and either logs or powers.


::: {.callout-caution title="Examples of significant figures in mixed calculations."}
Determine the change in Gibbs free energy, $\Delta G$, for a reaction at 25 K, if $\Delta H = -84.3$ kJ mol$^{-1}$ and $\Delta S = 0.164$ kJ K$^{-1}$ mol$^{-1}$.

$\Delta G = \Delta H - T \Delta S$

The first step we have to do here is to calculate $T$ in K. Although this isn't formally in a bracket, we need to do this first to get our temperature in the correct units. This is an addition calculation, so we need to consider the number of decimal places in our answer.

So $T$ = 25 ºC + 273.15 K = 298 K (we should be considering this value to have 3 sig figs).

The next step is to calculate $T \Delta S$. This is a multiplication calculation, so we need to consider the number of significant figures in our answer.

So $T \Delta S = 298 \textrm{ K} \times 0.164 \textrm{ kJ K}^{-1} \textrm{ mol}^{-1} = 48.9 \textrm{ kJ mol}^{-1}$

The final step is to calculate $\Delta G = \Delta H - T \Delta S$. This is a subtraction calculation, so we need to consider the number of decimal places in our answer.

So $\Delta G = -84.3 \textrm{ kJ mol}^{-1} - (48.9 \textrm{ kJ mol}^{-1}) = -133.2 \textrm{ kJ mol}^{-1}$

This is potentially a confusing result if you don't have a good understanding of significant figures, as the final answer has more significant figures than the values we used in our calculation.
:::

::: {.callout-caution title="Examples of significant figures in mixed calculations."}
Determine the rate constant for the first order reaction where the initial concentration of the reactant is 0.100 M, the final concentration of the reactant is 0.127 M and the time taken for this change is 70 minutes.

If it is a first order reaction, then we can use the equation:

$[A] = [A]_0 e^{-kt}$

which we can rearrange to give us:

$k = \frac{1}{t} \ln \frac{[A]_0}{[A]}$

The first step is to calculate the ratio of the initial and final concentrations. This is a division calculation, so we need to consider the number of significant figures in our answer.

$\frac{[A]_0}{[A]} = \frac{0.100 \textrm{ M}}{0.127 \textrm{ M}} = 0.787$

The next step is to calculate the natural log of this value. This is a log calculation, so we need to consider the number of significant figures in our answer.

$\ln \frac{[A]_0}{[A]} = \ln(0.787) = -0.2395$

In this case we are taking the log of a value less than 1 so we should gain a significant figure, so our answer has 4 significant figures.

The final step is to calculate the rate constant $k$. This is a multiplication calculation, so we need to consider the number of significant figures in our answer.

$k = \frac{1}{t} \ln \frac{[A]_0}{[A]} = \frac{1}{70 \textrm{ min}} \times (-0.240) = -0.0034 \textrm{ min}^{-1}$

Here our time, $t$, has the fewest significant figures, so our answer should be reported to just 2 significant figures.
:::


### Exercises with mixed calculations.

#### Self check on our learning so far. {#sec-Selfcheckmixed}

In each case the equation you will need to use is given above the question, but it may be in a form that you need to rearrange to get the value you are looking for.

$\Delta G = \Delta H - T \Delta S$.

:::{.callout-note collapse="true"}
## Determine the Gibbs free energy change at 50 ºC for the formation of calcite (CaCO$-3$), given the enthapy of formation is -1207 kJ mol$^{-1}$ and the entropy of formation is +92.9 J K$^{-1}$ mol$^{-1}$.

$\Delta G = -1237 \textrm{ kJ mol}^{-1}$

To do this we need the equation $\Delta G = \Delta H - T \Delta S$.

First we need to convert our temperature to Kelvin, which is an addition calculation, so we need to consider the number of decimal places in our answer.

T = 50 ºC + 273.15 K = 323 K (we should be considering this value to have 3 sig figs).

Next we need to calculate $T \Delta S$. This is a multiplication calculation, so we need to consider the number of significant figures in our answer.

$T \Delta S = 323 \textrm{ K} \times 92.9 \textrm{ J K}^{-1} \textrm{ mol}^{-1} = 3.00 \times 10^4 \textrm{ J mol}^{-1}$ = 30.0 kJ mol$^{-1}$

Finally we can calculate $\Delta G = \Delta H - T \Delta S$. This is a subtraction calculation, so we need to consider the number of decimal places in our answer.

$\Delta G = -1207 \textrm{ kJ mol}^{-1} - 30.0 \textrm{ kJ mol}^{-1} = -1237 \textrm{ kJ mol}^{-1}$

:::

$\Delta G = -RT \ln K$

:::{.callout-note collapse="true"}
## Determine the equilibrium constant, $K$, for a reaction with a Gibbs free energy change of -10.45 kJ mol$^{-1}$ at 36.5 ºC.

$K = 57.9

The first step here is to rearrange the equation to give us $K$ as the subject.

$K = e^{-\frac{\Delta G}{RT}}$

Now we need to convert our temperature to Kelvin, which is an addition calculation, so we need to consider the number of decimal places in our answer.

T = 36.5 ºC + 273.15 K = 309.6 K (this value has been rounded to even and has 4 significant figures).

Next we need to calculate the value of $\frac{\Delta G}{RT}$. This is a multiplication/division calculation, so we need to consider the number of significant figures in our answer.

$\frac{\Delta G}{RT} = \frac{-10.45 \textrm{ kJ mol}^{-1}}{8.31447 \textrm{ J K}^{-1} \textrm{ mol}^{-1} \times 309.6 \textrm{ K}}$

rewriting our units of kJ to J we have:

$\frac{\Delta G}{RT} = \frac{-10.45 \times 10^3 \textrm{ J mol}^{-1}}{8.31447 \textrm{ J K}^{-1} \textrm{ mol}^{-1} \times 309.6 \textrm{ K}}$

$\frac{\Delta G}{RT} = -4.060$ - our fewest significant figures is 4, so our answer should be reported to 4 significant figures.

now we can calculate $K = e^{-\frac{\Delta G}{RT}}$.

$K = e^{4.060} = 57.9$ - because our exponent is greater than 1, we should loose a significant figure in our answer, so 4 significant figures in our exponent gives us 3 significant figures in our answer.


Finally we can calculate $K = e^{-\frac{\Delta G}{RT}}$. This is an exponent calculation, so we need to consider the number of significant figures in our answer.
:::

$E = E^0 - \frac{RT}{nF} \ln \frac{\{\text{products}\}}{\{\text{reactants}\}}$

Recall - values in curly brackets are activities.

:::{.callout-note collapse="true"}
## Determine the cell potential, $E$ for a reaction at exactly 20 ºC, with a standard cell potential, $E^0$, of 1.012 V, a number of electrons transfered, $n$, of 2, and activities of the products and reactants of 0.563 and 1.263 respectively.

$V = 1.022$ V

First we need to deal with the 'implied' brackets:

$\frac{\{\text{products}\}}{\{\text{reactants}\}} = \frac{0.563}{1.263} = 0.446$ 

Three significant figures in our answer because our fewest significant figures in our calculation is 3.

$T = 20 ºC + 273.15 K = 293.15 K$

The temperature in the question is described as "exactly" 20 ºC, so we can consider this to have infinite significant figures. Therefore our temperature in Kelvin will also have infinite significant figures.

The next highest priority operation is the log:

$\ln \frac{\{\text{products}\}}{\{\text{reactants}\}} = \ln(0.446) = -0.807$.

The value we are taking the log of is between 0 and the base, so we do not gain a significant figure in our answer.

The next highest priority operation is the multiplication/division:

$\frac{RT}{nF}\ln \frac{\{\text{products}\}}{\{\text{reactants}\}}  = \frac{8.31447 \textrm{ J K}^{-1} \textrm{ mol}^{-1} \times 293.15 \textrm{ K}}{2 \times 96485 \textrm{ C mol}^{-1}} \times (-0.807) = -0.0102$ V 

The final step is to calculate the cell potential, $E$. This is a subtraction calculation, so we need to consider the number of decimal places in our answer.

$E = E^0 - \frac{RT}{nF} \ln \frac{\{\text{products}\}}{\{\text{reactants}\}} = 1.012 \textrm{ V} - (-0.0102 \textrm{ V}) = 1.022 \textrm{ V}$

:::

#### Self assessment question on mixed calculations.
